<?php

declare(strict_types=1);

namespace NodesWars\Api\Engine;

/**
 * GENERATED by scripts/gen-weapons.mjs from data/weapons.json.
 * Do not edit by hand. Run `pnpm gen:weapons` after changing the source.
 */
final class Weapons
{
    /** @var array<string, array{id: string, name: string, blastRadiusM: int, damage: int, falloff: string}> */
    public const ALL = [
        'scout' => ['id' => 'scout', 'name' => 'Scout Round', 'blastRadiusM' => 15, 'damage' => 20, 'falloff' => 'flat'],
        'light' => ['id' => 'light', 'name' => 'Light Shell', 'blastRadiusM' => 25, 'damage' => 35, 'falloff' => 'linear'],
        'medium' => ['id' => 'medium', 'name' => 'Medium Shell', 'blastRadiusM' => 50, 'damage' => 55, 'falloff' => 'linear'],
        'heavy' => ['id' => 'heavy', 'name' => 'Heavy Shell', 'blastRadiusM' => 100, 'damage' => 80, 'falloff' => 'linear'],
        'siege' => ['id' => 'siege', 'name' => 'Siege Mortar', 'blastRadiusM' => 200, 'damage' => 120, 'falloff' => 'linear'],
    ];

    /** @var list<string> */
    public const IDS = ['scout', 'light', 'medium', 'heavy', 'siege'];
}
