// GENERATED by scripts/gen-weapons.mjs from data/weapons.json.
// Do not edit by hand. Run `pnpm gen:weapons` after changing the source.

export type WeaponId = 'scout' | 'light' | 'medium' | 'heavy' | 'siege';

export type Falloff = 'flat' | 'linear';

export interface WeaponSpec {
  readonly id: WeaponId;
  readonly name: string;
  /** Blast radius in metres. */
  readonly blastRadiusM: number;
  /** Damage at the centre of the blast, in HP. */
  readonly damage: number;
  readonly falloff: Falloff;
}

export const WEAPONS: Readonly<Record<WeaponId, WeaponSpec>> = {
  scout: { id: 'scout', name: 'Scout Round', blastRadiusM: 15, damage: 20, falloff: 'flat' },
  light: { id: 'light', name: 'Light Shell', blastRadiusM: 25, damage: 35, falloff: 'linear' },
  medium: { id: 'medium', name: 'Medium Shell', blastRadiusM: 50, damage: 55, falloff: 'linear' },
  heavy: { id: 'heavy', name: 'Heavy Shell', blastRadiusM: 100, damage: 80, falloff: 'linear' },
  siege: { id: 'siege', name: 'Siege Mortar', blastRadiusM: 200, damage: 120, falloff: 'linear' },
};

export const WEAPON_IDS: readonly WeaponId[] = ['scout', 'light', 'medium', 'heavy', 'siege'];
