// Generates the per-language weapon tables from data/weapons.json.
//
// The two engines must agree exactly, so neither reads the JSON at runtime:
// both get a generated constant instead. data/weapons.json is the only file a
// human edits. Run `pnpm gen:weapons` after changing it.
//
// `pnpm gen:weapons:check` regenerates into memory and fails if the committed
// output differs, which is what CI runs.

import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'data/weapons.json';
const TS_OUT = 'packages/engine/src/weapons.generated.ts';
const PHP_OUT = 'apps/api/src/Engine/Weapons.php';

const VALID_FALLOFF = ['flat', 'linear'];

function load() {
  const { weapons } = JSON.parse(readFileSync(SOURCE, 'utf8'));

  if (!Array.isArray(weapons) || weapons.length === 0) {
    throw new Error(`${SOURCE}: weapons must be a non-empty array`);
  }

  const seen = new Set();
  for (const w of weapons) {
    for (const field of ['id', 'name', 'blastRadiusM', 'damage', 'falloff']) {
      if (w[field] === undefined) {
        throw new Error(`${SOURCE}: weapon ${w.id ?? '(no id)'} is missing ${field}`);
      }
    }
    if (seen.has(w.id)) throw new Error(`${SOURCE}: duplicate weapon id ${w.id}`);
    seen.add(w.id);

    if (!/^[a-z][a-z0-9_]*$/.test(w.id)) {
      throw new Error(`${SOURCE}: weapon id ${w.id} must be lower_snake_case`);
    }
    // Radii and damage are converted with fromInt, which rejects non-integers.
    for (const field of ['blastRadiusM', 'damage']) {
      if (!Number.isInteger(w[field]) || w[field] <= 0) {
        throw new Error(`${SOURCE}: ${w.id}.${field} must be a positive integer`);
      }
    }
    if (!VALID_FALLOFF.includes(w.falloff)) {
      throw new Error(
        `${SOURCE}: ${w.id}.falloff must be one of ${VALID_FALLOFF.join(', ')}, got ${w.falloff}`,
      );
    }
  }

  return weapons;
}

// Both target languages are configured for single-quoted strings, so emit
// them that way rather than exempting the generated files from the linters.
function sq(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderTs(weapons) {
  const ids = weapons.map((w) => `'${w.id}'`).join(' | ');
  const entries = weapons
    .map(
      (w) =>
        `  ${w.id}: { id: '${w.id}', name: ${sq(w.name)}, ` +
        `blastRadiusM: ${w.blastRadiusM}, damage: ${w.damage}, falloff: '${w.falloff}' },`,
    )
    .join('\n');

  return `// GENERATED by scripts/gen-weapons.mjs from data/weapons.json.
// Do not edit by hand. Run \`pnpm gen:weapons\` after changing the source.

export type WeaponId = ${ids};

export type Falloff = 'flat' | 'linear';

export interface WeaponSpec {
  readonly id: WeaponId;
  readonly name: string;
  /** Blast radius in metres. */
  readonly blastRadiusM: number;
  /** Damage at the centre of the blast, in HP. */
  readonly damage: number;
  readonly falloff: Falloff;
}

export const WEAPONS: Readonly<Record<WeaponId, WeaponSpec>> = {
${entries}
};

export const WEAPON_IDS: readonly WeaponId[] = [${weapons.map((w) => `'${w.id}'`).join(', ')}];
`;
}

function renderPhp(weapons) {
  const entries = weapons
    .map(
      (w) =>
        `        '${w.id}' => ['id' => '${w.id}', 'name' => ${sq(w.name)}, ` +
        `'blastRadiusM' => ${w.blastRadiusM}, 'damage' => ${w.damage}, 'falloff' => '${w.falloff}'],`,
    )
    .join('\n');

  return `<?php

declare(strict_types=1);

namespace NodesWars\\Api\\Engine;

/**
 * GENERATED by scripts/gen-weapons.mjs from data/weapons.json.
 * Do not edit by hand. Run \`pnpm gen:weapons\` after changing the source.
 */
final class Weapons
{
    /** @var array<string, array{id: string, name: string, blastRadiusM: int, damage: int, falloff: string}> */
    public const ALL = [
${entries}
    ];

    /** @var list<string> */
    public const IDS = [${weapons.map((w) => `'${w.id}'`).join(', ')}];
}
`;
}

const weapons = load();
const outputs = [
  [TS_OUT, renderTs(weapons)],
  [PHP_OUT, renderPhp(weapons)],
];

const checkOnly = process.argv.includes('--check');
let drift = false;

for (const [path, contents] of outputs) {
  if (checkOnly) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      current = '';
    }
    if (current !== contents) {
      console.error(`${path} is out of date with ${SOURCE}. Run: pnpm gen:weapons`);
      drift = true;
    }
  } else {
    writeFileSync(path, contents);
    console.log(`${path}: ${weapons.length} weapons`);
  }
}

if (drift) process.exit(1);
if (checkOnly) console.log(`Generated weapon tables match ${SOURCE}.`);
