name: Auto fix

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  autofix:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'auto-fix')
    name: Run formatters
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref || github.ref }}

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Prettier
        run: pnpm format

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_pgsql, sodium
          tools: composer:v2

      - name: PHP install
        working-directory: apps/api
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: PHP CS Fixer
        working-directory: apps/api
        run: ./vendor/bin/php-cs-fixer fix

      - uses: autofix-ci/action@v1
        with:
          fail-fast: false
